name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: artauction/web/package-lock.json

      - name: Create .env file
        working-directory: ./artauction/web
        run: |
          echo "REACT_APP_SUPABASE_URL=${{ secrets.REACT_APP_SUPABASE_URL }}" >> .env
          echo "REACT_APP_SUPABASE_ANON_KEY=${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}" >> .env
          echo "REACT_APP_API_HOST=${{ secrets.REACT_APP_API_HOST }}" >> .env

      - name: Install dependencies
        working-directory: ./artauction/web
        run: npm ci

      - name: Build project
        working-directory: ./artauction/web
        run: npm run build --if-present

      - name: Run tests
        working-directory: ./artauction/web
        run: npm test

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: artauction/web/build
